### ISSUE TITLE
bower install html5-desktop-notifications doesn't work, needs version tag

### ISSUE THREAD

**Issue by sorin7486** [ttsvetko/HTML5-Desktop-Notifications#20]
I tried to add this library using bower and I'm getting an error:

bower html5-desktop-notifications#1.0.0     ENORESTARGET No tag found that was able to satisfy 1.0.0

I think you need to create a tag in the github repository with the version name.

**Comment by aacanakin** [comment]
+1
I'm using bower too. It doesn't work

**Comment by vdsabev** [comment]
+1, specifying a version doesn't work, but without it it installs fine.

**Comment by yayolius** [comment]
+1 common @ttsvetko we just need a tag in order to really user with bower, because at the end without that bower.json is there for nothing.

**Comment by varmint09** [comment]
+1

**Comment by micmmakarov** [comment]
+1

**Comment by onstottj** [comment]
+1

**Comment by daviddutch** [comment]
+1

**Comment by iBasit** [comment]
You can install it by ```bower install ttsvetko/HTML5-Desktop-Notifications --save```

**Comment by ttsvetko** [comment]
fixed.
