### ISSUE TITLE
How to get focus to a Chrome tab which created desktop notification?

### ISSUE THREAD

**Issue by phongdatgl** [ttsvetko/HTML5-Desktop-Notifications#21]
When click to notification, browser will be switch to tab created notification. 
Can you help me ?

**Comment by israfilkara** [comment]
You could try window.focus()

**Comment by ttsvetko** [comment]
Chrome should does this without any additional code. Tab management is not in the scope of this library. Also - i think it is impossible to switch to tab using js.
