### ISSUE TITLE
Timeout option is mentioned in docs but isn't supported in the code

### ISSUE THREAD

**Issue by vvolodin** [ttsvetko/HTML5-Desktop-Notifications#3]
Hi, your readme mentions timeout option to automatically close notifications but it doesn't work.

**Comment by sandeep-instinct** [comment]
Setting autoClose = 0 don't have any effect. Even if I set it to 0, the notification does close. I want notification to stay up as long as user cancels it or she follows the link inside it. Am I missing anything or shall I file a new bug?

**Comment by ttsvetko** [comment]
released new version. AutoClose option is removed as it is already not supported
