### ISSUE TITLE
osx chrome fullscreen

### ISSUE THREAD

**Issue by tablatronix** [ttsvetko/HTML5-Desktop-Notifications#32]
I have noticed that when in fullscreen I do not get the popups but they seem to fire, and show up if i change to windowed. anyone know if this is a chrome issue or limitation ?

**Comment by oliveratgithub** [comment]
Haven't tried reproducing this, but it's most likely a Chromium issue with the built in notifications (they should use the OS X notifications and not implement notifications themselves). Try searching if it has been reported already here - or file a new issue @tablatronix : https://code.google.com/p/chromium/issues/list

**Comment by ttsvetko** [comment]
If the issue still exists - it is Chromium issue. The current polyfill just reuse the browser's native notification functionality.

**Comment by vb93** [comment]
I am facing the same issue
