### ISSUE TITLE
API to disable notifications?

### ISSUE THREAD

**Issue by TsuiJie** [ttsvetko/HTML5-Desktop-Notifications#33]
Is there an API to disable/restore notification settings for all supported browsers?

**Comment by mcpDESIGNS** [comment]
You mean so that no other sites can send them to you?

**Comment by TsuiJie** [comment]
nope, only a switch for our own functionality. I'm using cookies to disable notifications but I'm looking for a more generic method.

**Comment by ttsvetko** [comment]
It's up to the developer/code logic whether notification should be shown. No API for dislabe/enable Notification functionality
