### ISSUE TITLE
Not able to get notification on IE11

### ISSUE THREAD

**Issue by Nileshdcool** [ttsvetko/HTML5-Desktop-Notifications#37]
Hi , 

I have downloaded the project from your git repository but I am not getting any notification for my IE11 which is running on my windows 10 os.

First thing which wasnt happening is clicking on enable me title doesnt doing anything also clicking for notification to apper for IE 11 doesnt receive anything 

Please suggest

**Comment by Nileshdcool** [comment]
![ie11](https://cloud.githubusercontent.com/assets/9494633/12441681/9646a9ea-bf6f-11e5-9b8f-45be65cfd229.PNG)

Please check my IE11 screen

**Comment by bugron** [comment]
@Nileshdcool thanks for posting this issue. Here below the [Browser support](https://github.com/ttsvetko/HTML5-Desktop-Notifications#browsers-support) table there is a note about IE that notifications are visible only while the Pinned site window is running. That means you [have to pin your tab](http://prntscr.com/9vy0m5). Only after that you'll get what you can see [here](https://github.com/ttsvetko/HTML5-Desktop-Notifications#screenshots) (IE9 running on Windows7 pic).
I've searched a bit and seems https://github.com/ukot/ie_web_notifications is a workaround for IE notifications but you have to install an app to be able to get those notifications (I've not tested it). Hope this helps.
Closing this issue. Feel free to reopen if you still experience problems, thanks.

**Comment by Nileshdcool** [comment]
Ok thanks man , desktop application wont be good option for me but , thanks for clearing other fator

**Comment by MikeRubio** [comment]
@bugron Hi, is it possible for you to share the Polyfill required to make the notifications work in IE 11? Thanks in advance.

**Comment by quongdang** [comment]
Hi,
After many years, but seems still don't have any solution for display Notification on IE. We can't force user to install .msi file to see the notification or pin the page to task-bar for see it.
I also try the Polyfill for notification but seems not working.
Anyone have idea for this one?
