### ISSUE TITLE
tag option is not working

### ISSUE THREAD

**Issue by iBasit** [ttsvetko/HTML5-Desktop-Notifications#38]
Hi, 

I have latest chrome. notification is showing twice, because I have two windows open.

I did pass tag value, but it seems not to be working. 

maybe it needs to be integer or need to be set some other way?

**Comment by sudofx** [comment]
This seems to work fine on Mac OS (10.11.4).

However, Ubuntu 16.04 and Windows 10 will repost notifications even if the tag is the same.

**Comment by WilliamHolmes** [comment]
@sudofx Do have a link to a tech note ? Thanks.

**Comment by sudofx** [comment]
I do not.

**Comment by ttsvetko** [comment]
new version released. The new version relays on the native Notification object. Tag option seems to work now.
