### ISSUE TITLE
For specific recipients 

### ISSUE THREAD

**Issue by bencagri** [ttsvetko/HTML5-Desktop-Notifications#39]
Hi there, thx for this beautiful repo.

I wonder is it possible to send notifications to recipients. 
Here is an example;
There are two user types.
- Authors
- Editors.

When author writes an entry, send notification to editors .
If one of editor approve entry, send notification to author. (Not all of the authors)

Thx.

**Comment by ttsvetko** [comment]
Hi, 

This piece of code only deals with Notifications displaying, you/your application/site is the one that should decide where to show or not a Notification.
