### ISSUE TITLE
Which files need to be hosted

### ISSUE THREAD

**Issue by pvnr0082t** [ttsvetko/HTML5-Desktop-Notifications#40]
Hi @ttsvetko ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this lib in cdnjs.
I know `desktop-notify.js` and `desktop-notify-min.js` need to be hosted for sure. Could you please tell me if `notifications.css` need to be added?
Thank you.

https://github.com/cdnjs/cdnjs/issues/8007

**Comment by ttsvetko** [comment]
Hi,
notifications.css should NOT be hosted.

**Comment by pvnr0082t** [comment]
Okay, thank you!! :+1:
