### ISSUE TITLE
Add git tags

### ISSUE THREAD

**Issue by pvnr0082t** [ttsvetko/HTML5-Desktop-Notifications#41]
Hi @ttsvetko ,
We found that the repo doesn't have any release. Could you please add git tags so that the git auto-updater in [cdnjs](https://github.com/cdnjs/cdnjs) can recognize the correct version and automatically update the repo?
Thank you.

https://github.com/cdnjs/cdnjs/issues/8007

**Comment by ttsvetko** [comment]
added tag v0.2.0
