### ISSUE TITLE
Win 10, IE 11 occurs error. 

### ISSUE THREAD

**Issue by tsogtbayar0821** [ttsvetko/HTML5-Desktop-Notifications#47]
"Promise is not defined"
http://prntscr.com/e9qp92

I am working on Win 10 using IE 11, but doesn't work notification.js.
works well in Edge.

**Comment by tsogtbayar0821** [comment]
It was IE bug.
https://github.com/github/fetch/issues/114

**Comment by ttsvetko** [comment]
Yep, Promises are not supported in IE11. So you need to add Promise polyfill as is noted into the Readme file:
[IE 9][IE 10] Does not support Promise. Polyfill required.

**Comment by Rajiv-Kulkarni** [comment]
Hi,
I am trying to run it from an asp.net mvc app and getting the IE11 Promise not defined error. Where can I get an appropriate Polyfill for the Promise? Thanks.
