### ISSUE TITLE
onclick / onclose events as options

### ISSUE THREAD

**Issue by justmarkup** [ttsvetko/HTML5-Desktop-Notifications#5]
I think it would be very handy to be able to attach onclick / onclose events to a notification as an option. I am happy to add this, or do you prefer do not have them in the code?

**Comment by maxnowack** [comment]
@vrialland please create a pull request for your change, to get this issue fixed

**Comment by GFoley83** [comment]
+1 This really should have been merged by now.

**Comment by ttsvetko** [comment]
Added in v0.3

Use the native addEventListener method to attach click/close/show events to the notification. It is recommended into the spec to AVOID using onclick/onclose/onshow.


var n = new Notification('title');
n.addEventListener('click', function(event) {
   // your body here
})
