### ISSUE TITLE
Fallback for other browsers

### ISSUE THREAD

**Issue by chrisgraham** [ttsvetko/HTML5-Desktop-Notifications#7]
Personally I think this is a neat "better than nothing"...

```
		} else if (win.external && win.external.msIsSiteMode()) { /* IE9+ */
			//Clear any previous notifications
			win.external.msSiteModeClearIconOverlay();
			win.external.msSiteModeSetIconOverlay('{$IMG;,notifications/notifications}', title);
			win.external.msSiteModeActivate();
			notification = {
				"ieVerification": ++ieVerification
			};
		} else
		{
			if (typeof window.focus!='undefined')
			{
				try
				{
					window.focus();
				}
				catch (e) {};
			}
		}
````

i.e. On IE8 etc, it will try and auto-focus the Window when a notification happens.

Maybe it should be optional, or people should just implement themselves, but for my purposes it works well :).

**Comment by ttsvetko** [comment]
Well, personally prefer to leave this to the developer and specific case.
I've pushed a new version of the polyfill and soon will provide ability to attach event listeners like show/click/close to the IE "notifications" ... so, the developer can attach listener when notification occurs and focus the window.
