### ISSUE TITLE
Auto-focus tab when clicked

### ISSUE THREAD

**Issue by chrisgraham** [ttsvetko/HTML5-Desktop-Notifications#8]
When clicking the notification using Chrome on Mac, it focus's Chrome, but not the originating tab. This works around that nicely:

```
notification.onclick=function() {
	try
	{
		window.focus();
	}
	catch (ex) {};
};
```

(the try...catch is just because popup blockers sometimes set window.focus to null)

**Comment by allenfantasy** [comment]
Has same issue here.

As @chrisgraham mentioned (also mentioned [here](http://stackoverflow.com/questions/4906976/how-to-get-focus-to-a-chrome-tab-which-created-desktop-notification)), you can just add an `onclick` handler , thus when the popup desktop notification is clicked, the original tab would be focused. However, this repo's API wrap the notification object so there's no way to add this event handler via the public API.

So I just dive into the code and add some code as workaround: 

In the `getNotification` function:
```js
function getNotification(title, options) {
  // ...
  // workaround here
  notification.onclick = function(x) { 
     try {
       window.focus();
       this.cancel(); 
     }
     catch (ex) {
     }  
  };
  return notification;
}
```

Another way is to expose the original notification object in the `createNotification` API.

**Comment by ttsvetko** [comment]
Nice workaround, but i would like to keep the focus to the browsers native functionality. You could attach click event listener and focus the window in your code.
